# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            rm-dash-r
tagline:          'EJ Bensing\'s Blog'
description:      'A Blog'
url:              http://www.rm-dash-r.com
baseurl:          /

author:
  name:           'EJ Bensing'
  url:            https://github.com/ebensing

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ebensing/ebensing.github.io
