markdown: redcarpet
highlighter: pygments

permalink: pretty
relative_permalinks: true

title:            rm-dash-r
tagline:          'EJ Bensings Blog'
description:      'A Blog'
url:              http://www.rm-dash-r.com
baseurl:          /

author:
  name:           'EJ Bensing'
  url:            https://github.com/ebensing

paginate:         5

version:          2.1.0

github:
  repo:           https://github.com/ebensing/ebensing.github.io
